from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol


class CommitmentsRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, commitment_id: str) -> dict[str, Any] | None: ...
    def list_tasks_for_user(self, user_id: str, commitment_id: str | None = None) -> list[dict[str, Any]]: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, commitment_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def create_tasks(self, user_id: str, rows: list[dict[str, Any]]) -> None: ...
    def create_time_spine(self, user_id: str, data: dict[str, Any]) -> None: ...
    def get_time_spine(self, user_id: str, commitment_id: str) -> dict[str, Any] | None: ...
    def update_time_spine(self, user_id: str, commitment_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    def approve_intake(self, user_id: str, run_id: str, idempotency_key: str, items: list[dict[str, Any]]) -> dict[str, Any]: ...


class FocusRepository(Protocol):
    def list_for_user(self, user_id: str, start_at: datetime | None = None, end_at: datetime | None = None) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, block_id: str) -> dict[str, Any] | None: ...
    def get_active(self, user_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, block_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def complete_transaction(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class PlanningRepository(Protocol):
    def list_pending(self, user_id: str) -> list[dict[str, Any]]: ...
    def list_calendar_events(self, user_id: str, start_at: datetime, end_at: datetime) -> list[dict[str, Any]]: ...
    def get_proposal(self, user_id: str, proposal_id: str) -> dict[str, Any] | None: ...
    def create_proposal(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_proposal(self, user_id: str, proposal_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def approve_recovery(self, user_id: str, proposal_id: str, idempotency_key: str, focus_block_id: str | None) -> dict[str, Any]: ...
    def approve_adaptive_plan(self, user_id: str, proposal_id: str, idempotency_key: str, block_ids: list[str]) -> dict[str, Any]: ...


class ReflectionsRepository(Protocol):
    def list_recent(self, user_id: str, commitment_id: str) -> list[dict[str, Any]]: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class WorkflowTraceRepository(Protocol):
    def create_run(self, user_id: str, run_type: str, input_summary: dict[str, Any], *, workflow_id: str) -> str: ...
    def complete_run(self, user_id: str, run_id: str, output_summary: dict[str, Any] | None = None) -> None: ...
    def fail_run(self, user_id: str, run_id: str, error_code: str) -> None: ...
    def append(self, user_id: str, run_id: str, event: dict[str, Any]) -> None: ...
    def list_events(self, user_id: str, run_id: str) -> list[dict[str, Any]]: ...


class GoogleConnectionRepository(Protocol):
    def get_metadata(self, user_id: str) -> dict[str, Any] | None: ...
    def get_status(self, user_id: str) -> dict[str, Any]: ...


class PlanningProfileRepository(Protocol):
    def get(self, user_id: str) -> dict[str, Any]: ...
    def update(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def reset(self, user_id: str) -> dict[str, Any]: ...


class RecommendationFeedbackRepository(Protocol):
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_for_user(self, user_id: str, limit: int = 50) -> list[dict[str, Any]]: ...


class ProjectsRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, project_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, project_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class OutcomesRepository(Protocol):
    def list_for_user(self, user_id: str, project_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, outcome_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, outcome_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def link_work(self, user_id: str, outcome_id: str, commitment_ids: list[str], task_ids: list[str]) -> None: ...


class RoutinesRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, routine_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, routine_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def upsert_occurrence(self, user_id: str, routine_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_occurrences(self, user_id: str, start_at: datetime, end_at: datetime) -> list[dict[str, Any]]: ...


class WeeklyPlansRepository(Protocol):
    def get_for_user(self, user_id: str, plan_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, plan_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def approve(self, user_id: str, plan_id: str, idempotency_key: str, block_ids: list[str]) -> dict[str, Any]: ...


@dataclass(frozen=True)
class RepositorySet:
    commitments: CommitmentsRepository
    focus: FocusRepository
    planning: PlanningRepository
    reflections: ReflectionsRepository
    traces: WorkflowTraceRepository
    google_connections: GoogleConnectionRepository
    planning_profiles: PlanningProfileRepository
    projects: ProjectsRepository
    outcomes: OutcomesRepository
    routines: RoutinesRepository
    weekly_plans: WeeklyPlansRepository
    feedback: RecommendationFeedbackRepository
