from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol


class CommitmentsRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, commitment_id: str) -> dict[str, Any] | None: ...
    def list_tasks_for_user(self, user_id: str, commitment_id: str | None = None) -> list[dict[str, Any]]: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, commitment_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def create_tasks(self, user_id: str, rows: list[dict[str, Any]]) -> None: ...
    def create_time_spine(self, user_id: str, data: dict[str, Any]) -> None: ...
    def get_time_spine(self, user_id: str, commitment_id: str) -> dict[str, Any] | None: ...
    def update_time_spine(self, user_id: str, commitment_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...
    def approve_intake(self, user_id: str, run_id: str, idempotency_key: str, items: list[dict[str, Any]]) -> dict[str, Any]: ...


class FocusRepository(Protocol):
    def list_for_user(self, user_id: str, start_at: datetime | None = None, end_at: datetime | None = None) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, block_id: str) -> dict[str, Any] | None: ...
    def get_active(self, user_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, block_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def complete_transaction(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class PlanningRepository(Protocol):
    def list_pending(self, user_id: str) -> list[dict[str, Any]]: ...
    def list_calendar_events(self, user_id: str, start_at: datetime, end_at: datetime) -> list[dict[str, Any]]: ...
    def get_proposal(self, user_id: str, proposal_id: str) -> dict[str, Any] | None: ...
    def create_proposal(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_proposal(self, user_id: str, proposal_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def approve_recovery(self, user_id: str, proposal_id: str, idempotency_key: str, focus_block_id: str | None) -> dict[str, Any]: ...
    def approve_adaptive_plan(self, user_id: str, proposal_id: str, idempotency_key: str, block_ids: list[str]) -> dict[str, Any]: ...
    def upsert_external_calendar_event(self, user_id: str, provider: str, item: dict[str, Any]) -> None: ...


class ReflectionsRepository(Protocol):
    def list_recent(self, user_id: str, commitment_id: str) -> list[dict[str, Any]]: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class WorkflowTraceRepository(Protocol):
    def create_run(self, user_id: str, run_type: str, input_summary: dict[str, Any], *, workflow_id: str) -> str: ...
    def complete_run(self, user_id: str, run_id: str, output_summary: dict[str, Any] | None = None) -> None: ...
    def fail_run(self, user_id: str, run_id: str, error_code: str) -> None: ...
    def append(self, user_id: str, run_id: str, event: dict[str, Any]) -> None: ...
    def list_events(self, user_id: str, run_id: str) -> list[dict[str, Any]]: ...


class GoogleConnectionRepository(Protocol):
    def get_metadata(self, user_id: str) -> dict[str, Any] | None: ...
    def get_status(self, user_id: str) -> dict[str, Any]: ...


class PlanningProfileRepository(Protocol):
    def get(self, user_id: str) -> dict[str, Any]: ...
    def update(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def reset(self, user_id: str) -> dict[str, Any]: ...


class RecommendationFeedbackRepository(Protocol):
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_for_user(self, user_id: str, limit: int = 50) -> list[dict[str, Any]]: ...


class MemoryItemsRepository(Protocol):
    def list_for_user(self, user_id: str, category: str | None = None, project_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, memory_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, memory_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class KnowledgeRepository(Protocol):
    def list_sources(self, user_id: str, project_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_source(self, user_id: str, source_id: str) -> dict[str, Any] | None: ...
    def create_failed_source(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_source(self, user_id: str, source_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def ingest(self, user_id: str, idempotency_key: str, source: dict[str, Any], chunks: list[dict[str, Any]]) -> dict[str, Any]: ...
    def retrieve(self, user_id: str, query: str, query_embedding: list[float], project_id: str | None, limit: int) -> list[dict[str, Any]]: ...


class ContextPackRepository(Protocol):
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_for_user(self, user_id: str, pack_id: str) -> dict[str, Any] | None: ...


class IntegrationsRepository(Protocol):
    def list_connections(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_connection(self, user_id: str, provider: str) -> dict[str, Any] | None: ...
    def create_connection(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_connection(self, user_id: str, connection_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_items(self, user_id: str, provider: str | None = None, project_id: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    def get_item(self, user_id: str, item_id: str) -> dict[str, Any] | None: ...
    def upsert_item(self, user_id: str, connection_id: str, provider: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_proposals(self, user_id: str, status: str = "pending") -> list[dict[str, Any]]: ...
    def create_proposal(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_proposal(self, user_id: str, proposal_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def approve_proposal(self, user_id: str, proposal_id: str, action_type: str, project_id: str | None) -> dict[str, Any]: ...
    def append_audit(self, user_id: str, data: dict[str, Any]) -> None: ...


class OperationalRepository(Protocol):
    def consume_budget(self, user_id: str, category: str, user_limit: int, global_limit: int, units: int = 1) -> dict[str, Any]: ...
    def append_audit(self, user_id: str | None, data: dict[str, Any]) -> None: ...
    def inventory(self, user_id: str) -> dict[str, int]: ...
    def export(self, user_id: str) -> dict[str, Any]: ...
    def delete_knowledge_source(self, user_id: str, source_id: str) -> dict[str, Any]: ...
    def delete_account(self, user_id: str, confirmation: str) -> dict[str, Any]: ...


class ProjectsRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, project_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, project_id: str, data: dict[str, Any]) -> dict[str, Any]: ...


class OutcomesRepository(Protocol):
    def list_for_user(self, user_id: str, project_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, outcome_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, outcome_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def link_work(self, user_id: str, outcome_id: str, commitment_ids: list[str], task_ids: list[str]) -> None: ...


class RoutinesRepository(Protocol):
    def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_for_user(self, user_id: str, routine_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, routine_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def upsert_occurrence(self, user_id: str, routine_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_occurrences(self, user_id: str, start_at: datetime, end_at: datetime) -> list[dict[str, Any]]: ...


class WeeklyPlansRepository(Protocol):
    def get_for_user(self, user_id: str, plan_id: str) -> dict[str, Any] | None: ...
    def create(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, user_id: str, plan_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def approve(self, user_id: str, plan_id: str, idempotency_key: str, block_ids: list[str]) -> dict[str, Any]: ...


@dataclass(frozen=True)
class RepositorySet:
    commitments: CommitmentsRepository
    focus: FocusRepository
    planning: PlanningRepository
    reflections: ReflectionsRepository
    traces: WorkflowTraceRepository
    google_connections: GoogleConnectionRepository
    planning_profiles: PlanningProfileRepository
    projects: ProjectsRepository
    outcomes: OutcomesRepository
    routines: RoutinesRepository
    weekly_plans: WeeklyPlansRepository
    feedback: RecommendationFeedbackRepository
    memory: MemoryItemsRepository
    knowledge: KnowledgeRepository
    context_packs: ContextPackRepository
    integrations: IntegrationsRepository
    operations: OperationalRepository | None = None
