[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*
    ignore:All support for the `google.generativeai` package has ended.*
    ignore:The 'timeout' parameter is deprecated.*
    ignore:The 'verify' parameter is deprecated.*
