from app.strategies.models import StrategyDefinition, StrategyId

STRATEGIES = {
    StrategyId.EISENHOWER: StrategyDefinition(id=StrategyId.EISENHOWER, name="Eisenhower triage", eligibility=("urgency and importance are known",), evidence_requirements=("urgency", "importance"), contraindications=("delegation without a real delegation path",), explanation_template="Triage by urgency and importance, then confirm destructive or delegated actions."),
    StrategyId.BATCHING: StrategyDefinition(id=StrategyId.BATCHING, name="Task batching", eligibility=("similar low-switch-cost tasks exist",), evidence_requirements=("shared context", "task count"), contraindications=("interrupting active deep work",), explanation_template="Collect similar quick tasks into one bounded batch."),
    StrategyId.CONTINUITY: StrategyDefinition(id=StrategyId.CONTINUITY, name="Continuity recovery", eligibility=("a repeated behavior was missed",), evidence_requirements=("recent completion history",), contraindications=("punitive streak framing",), explanation_template="Restart with a smaller repetition and preserve continuity without punishment."),
    StrategyId.FOCUS_INTERVAL: StrategyDefinition(id=StrategyId.FOCUS_INTERVAL, name="Focus interval", eligibility=("a meaningful task needs protected attention",), evidence_requirements=("task estimate or user preference",), contraindications=("fixed universal interval",), explanation_template="Use a configurable focus interval with pause, finish, stop, and stuck paths."),
    StrategyId.CONSTRAINED_DAY: StrategyDefinition(id=StrategyId.CONSTRAINED_DAY, name="Constrained-day plan", eligibility=("planned work exceeds capacity",), evidence_requirements=("free minutes", "work estimates"), contraindications=("forcing literal three-hour blocks",), explanation_template="Protect one major outcome, select short avoided tasks, and retain essential maintenance."),
    StrategyId.QUICK_ACTION: StrategyDefinition(id=StrategyId.QUICK_ACTION, name="Quick action", eligibility=("task is below the configured threshold",), evidence_requirements=("estimate", "focus state"), contraindications=("active deep work",), explanation_template="Complete the small task now when switching cost is low."),
    StrategyId.ENERGY_AWARE: StrategyDefinition(id=StrategyId.ENERGY_AWARE, name="Energy-aware scheduling", eligibility=("enough user-specific evidence exists",), evidence_requirements=("sample size", "confidence"), contraindications=("universal productive hours", "medical claims"), explanation_template="Match work to observed energy patterns as a low-stakes recommendation."),
    StrategyId.DIGITAL_RESET: StrategyDefinition(id=StrategyId.DIGITAL_RESET, name="Digital reset", eligibility=("a transition or break would help",), evidence_requirements=("user preference",), contraindications=("surveillance", "device control"), explanation_template="Offer an optional screen-free transition."),
    StrategyId.TIME_BLOCKING: StrategyDefinition(id=StrategyId.TIME_BLOCKING, name="Time blocking", eligibility=("work needs scheduling",), evidence_requirements=("availability", "duration", "buffers"), contraindications=("calendar overlap",), explanation_template="Reserve a realistic block with transition time."),
    StrategyId.REFLECTION_LENS: StrategyDefinition(id=StrategyId.REFLECTION_LENS, name="8/8/8 reflection", eligibility=("a consequential choice needs perspective",), evidence_requirements=("decision consequence",), contraindications=("routine tasks",), explanation_template="Compare the likely impact in roughly eight minutes, months, and years."),
}
