import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { apiFetch, apiUrl, getApiErrorMessage } from '../../lib/api';
import type { IntegrationCatalogItem } from '../../types/api';
import { Surface } from '../ui/primitives';

const LABELS: Record<string, string> = { google_calendar: 'Google Calendar', gmail: 'Gmail', github: 'GitHub', notion: 'Notion', outlook_calendar: 'Outlook Calendar', obsidian: 'Obsidian notes', microsoft_planner: 'Microsoft Planner' };
async function loadIntegrations() { const response = await apiFetch(apiUrl('/api/v1/integrations')); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Integration status is unavailable.')); return response.json() as Promise<{ integrations: IntegrationCatalogItem[] }>; }

export function IntegrationSettings() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['integrations'], queryFn: loadIntegrations }); const [notice, setNotice] = useState(''); const [obsidianFile, setObsidianFile] = useState<File | null>(null); const [resourceText, setResourceText] = useState<Record<string, string>>({});
  const sync = useMutation({ mutationFn: async (provider: string) => { const response = await apiFetch(apiUrl(`/api/v1/integrations/${provider}/sync`), { method: 'POST' }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Synchronization could not finish.')); return response.json(); }, onSuccess: async () => { setNotice('Context synchronized.'); await Promise.all([client.invalidateQueries({ queryKey: ['integrations'] }), client.invalidateQueries({ queryKey: ['external-proposals'] }), client.invalidateQueries({ queryKey: ['plan'] }), client.invalidateQueries({ queryKey: ['today'] })]); } });
  const disconnect = useMutation({ mutationFn: async (provider: string) => { const response = await apiFetch(apiUrl(`/api/v1/integrations/${provider}/disconnect`), { method: 'POST' }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'The connection could not be removed.')); }, onSuccess: async () => { setNotice('Connection removed and future synchronization stopped.'); await client.invalidateQueries({ queryKey: ['integrations'] }); } });
  const connectGoogle = useMutation({ mutationFn: async () => { const response = await apiFetch(apiUrl('/api/v1/google/auth/url')); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Google Calendar connection is unavailable.')); return response.json() as Promise<{ auth_url: string }>; }, onSuccess: data => window.location.assign(data.auth_url) });
  const importObsidian = useMutation({ mutationFn: async () => { if (!obsidianFile) throw new Error('Choose a Markdown file or ZIP.'); const body = new FormData(); body.append('file', obsidianFile); const response = await apiFetch(apiUrl('/api/v1/integrations/obsidian/import'), { method: 'POST', body }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'The selected notes could not be imported.')); return response.json() as Promise<{ imported: number; duplicates: number }>; }, onSuccess: async data => { setNotice(`${data.imported} note${data.imported === 1 ? '' : 's'} imported; ${data.duplicates} duplicate${data.duplicates === 1 ? '' : 's'} skipped.`); setObsidianFile(null); await client.invalidateQueries({ queryKey: ['knowledge'] }); } });
  const saveResources = useMutation({ mutationFn: async ({ provider, value }: { provider: string; value: string }) => { const response = await apiFetch(apiUrl(`/api/v1/integrations/${provider}/resources`), { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resources: value.split(',').map(item => item.trim()).filter(Boolean) }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Selected resources could not be saved.')); }, onSuccess: async () => { setNotice('Selected resources saved. The next sync will use only this list.'); await client.invalidateQueries({ queryKey: ['integrations'] }); } });
  return <Surface className="p-6"><h2 className="font-semibold">Integrations</h2><p className="mt-2 text-sm text-muted">External context is read-only, attributed, and never becomes a commitment or memory without your review.</p>
    {query.isPending ? <p className="mt-4 text-sm text-muted">Checking integrations…</p> : query.isError ? <p role="alert" className="mt-4 text-sm text-danger">Integration status is unavailable. <button className="font-semibold underline" onClick={() => query.refetch()}>Try again</button></p> : <div className="mt-4 divide-y divide-line">{query.data?.integrations.map(item => <div key={item.provider} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{LABELS[item.provider] ?? item.provider}</h3><p className="mt-1 text-sm text-muted">{item.message}</p></div><span className="rounded-full bg-accent-soft px-3 py-1 text-xs font-semibold text-accent-strong">{item.state.replaceAll('_', ' ')}</span></div>
      <details className="mt-3 text-sm"><summary className="cursor-pointer font-medium">Permissions and privacy</summary><p className="mt-2 text-muted">Read-only. Access is limited to {item.capabilities.flatMap(capability => capability.data_accessed).join(', ') || 'content you explicitly select'}.</p>{item.requested_scopes.length > 0 && <p className="mt-1 break-words text-xs text-faint">Requested permissions: {item.requested_scopes.join(', ')}</p>}{item.selected_resources.length > 0 && <p className="mt-1 text-xs text-faint">Selected: {item.selected_resources.join(', ')}</p>}</details>
      {item.last_success_at && <p className="mt-2 text-xs text-faint">Last successful sync {new Date(item.last_success_at).toLocaleString()}</p>}{item.state === 'connected' && ['github','notion','outlook_calendar','microsoft_planner'].includes(item.provider) && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><label className="label flex-1">Selected repositories, pages, calendars, or plans<input className="field mt-1" value={resourceText[item.provider] ?? item.selected_resources.join(', ')} onChange={event => setResourceText(current => ({ ...current, [item.provider]: event.target.value }))} placeholder="Enter provider IDs, separated by commas" /></label><button className="button-secondary self-end" onClick={() => saveResources.mutate({ provider: item.provider, value: resourceText[item.provider] ?? item.selected_resources.join(', ') })}>Save selection</button></div>}<div className="mt-3 flex flex-wrap gap-2">{item.provider === 'google_calendar' && item.configured && ['disconnected','expired','revoked'].includes(item.state) && <button className="button-primary" disabled={connectGoogle.isPending} onClick={() => connectGoogle.mutate()}>{connectGoogle.isPending ? 'Opening…' : 'Connect'}</button>}{item.state === 'connected' && <><button className="button-secondary" disabled={sync.isPending} onClick={() => sync.mutate(item.provider)}>Sync now</button><button className="button-secondary" disabled={disconnect.isPending} onClick={() => disconnect.mutate(item.provider)}>Disconnect</button></>}{item.state === 'degraded' && <button className="button-secondary" disabled={sync.isPending} onClick={() => sync.mutate(item.provider)}>Retry</button>}{item.provider === 'obsidian' && <><label className="button-secondary cursor-pointer">Choose Markdown or ZIP<input className="sr-only" type="file" accept=".md,.zip,text/markdown,application/zip" onChange={event => setObsidianFile(event.target.files?.[0] ?? null)} /></label><button className="button-primary" disabled={!obsidianFile || importObsidian.isPending} onClick={() => importObsidian.mutate()}>{importObsidian.isPending ? 'Importing…' : 'Import selected notes'}</button></>}</div>
    </div>)}</div>}{(sync.isError || disconnect.isError || connectGoogle.isError || importObsidian.isError || saveResources.isError) && <p role="alert" className="mt-3 text-sm text-danger">{(sync.error || disconnect.error || connectGoogle.error || importObsidian.error || saveResources.error)?.message}</p>}{notice && <p role="status" className="mt-3 text-sm text-success">{notice}</p>}
  </Surface>;
}
