import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { apiFetch, apiUrl, getApiErrorMessage } from '../../lib/api';
import type { PersonalPreferences } from '../../types/api';
import { LoadingState, Surface } from '../ui/primitives';

const STRATEGIES = [
  ['eisenhower_triage', 'Urgent and important'], ['task_batching', 'Task batching'], ['continuity_recovery', 'Routine continuity'],
  ['focus_interval', 'Focus intervals'], ['constrained_day', 'Constrained-day planning'], ['quick_action', 'Quick actions'], ['time_blocking', 'Time blocking'],
] as const;
const DURATIONS = [15, 20, 25, 30, 45, 60, 90];

async function loadPreferences(): Promise<PersonalPreferences> { const response = await apiFetch(apiUrl('/api/v1/settings/preferences')); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Personalization could not be loaded.')); return response.json(); }

export function PreferenceSettings() {
  const queryClient = useQueryClient(); const navigate = useNavigate();
  const query = useQuery({ queryKey: ['preferences'], queryFn: loadPreferences });
  const [form, setForm] = useState<PersonalPreferences | null>(null); const [notice, setNotice] = useState('');
  useEffect(() => { if (query.data) setForm(query.data); }, [query.data]);
  const save = useMutation({ mutationFn: async (value: PersonalPreferences) => { const response = await apiFetch(apiUrl('/api/v1/settings/preferences'), { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Personalization could not be saved.')); return response.json() as Promise<PersonalPreferences>; }, onSuccess: async data => { setForm(data); setNotice('Personalization saved.'); await Promise.all([queryClient.invalidateQueries({ queryKey: ['preferences'] }), queryClient.invalidateQueries({ queryKey: ['today'] }), queryClient.invalidateQueries({ queryKey: ['plan'] }), queryClient.invalidateQueries({ queryKey: ['routines'] })]); } });
  const reopen = useMutation({ mutationFn: async () => { const response = await apiFetch(apiUrl('/api/v1/settings/onboarding/reopen'), { method: 'POST' }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Setup could not be reopened.')); }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['onboarding'] }); navigate('/onboarding'); } });
  if (query.isPending || !form) return <LoadingState label="Loading personalization" />;
  if (query.isError) return <Surface className="p-6"><h2 className="font-semibold">Personalization unavailable</h2><p className="mt-2 text-sm text-muted">Keep using your current defaults, or try again.</p><button className="button-secondary mt-3" onClick={() => query.refetch()}>Try again</button></Surface>;
  const set = <K extends keyof PersonalPreferences>(key: K, value: PersonalPreferences[K]) => setForm(current => current ? { ...current, [key]: value } : current);
  const toggle = (key: 'preferred_focus_durations' | 'strategy_preferences', value: number | string) => setForm(current => { if (!current) return current; const values = current[key] as Array<number | string>; const next = values.includes(value) ? values.filter(item => item !== value) : [...values, value]; return { ...current, [key]: next } as PersonalPreferences; });
  return <form onSubmit={event => { event.preventDefault(); setNotice(''); save.mutate(form); }} className="space-y-5">
    <Surface className="p-6"><h2 className="font-semibold">Planning guidance</h2><p className="mt-1 text-sm text-muted">Control how often ChronOS speaks up and how much context it shows.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><Select label="Planning style" value={form.planning_style} onChange={value => set('planning_style', value as PersonalPreferences['planning_style'])} options={[['guided','Guided'],['balanced','Balanced'],['minimal','Minimal']]} /><Select label="Recommendation frequency" value={form.recommendation_frequency} onChange={value => set('recommendation_frequency', value as PersonalPreferences['recommendation_frequency'])} options={[['low','Low'],['normal','Normal'],['high','High']]} /><Select label="Explanation detail" value={form.explanation_detail} onChange={value => set('explanation_detail', value as PersonalPreferences['explanation_detail'])} options={[['brief','Brief'],['standard','Standard'],['detailed','Detailed']]} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select label="Quick tasks" value={form.quick_task_mode} onChange={value => set('quick_task_mode', value as PersonalPreferences['quick_task_mode'])} options={[['batch','Batch similar tasks'],['immediate','Surface immediately']]} /><Select label="Routine continuity" value={form.routine_continuity_preference} onChange={value => set('routine_continuity_preference', value as PersonalPreferences['routine_continuity_preference'])} options={[['gentle','Gentle minimum version'],['standard','Standard recovery'],['structured','Resume normal duration']]} /></div></Surface>
    <Surface className="p-6"><fieldset><legend className="font-semibold">Preferred focus durations</legend><div className="mt-3 flex flex-wrap gap-2">{DURATIONS.map(value => <label key={value} className="flex min-h-11 items-center gap-2 rounded-xl border border-line px-3 text-sm"><input type="checkbox" checked={form.preferred_focus_durations.includes(value)} onChange={() => toggle('preferred_focus_durations', value)} />{value} min</label>)}</div>{form.preferred_focus_durations.length === 0 && <p role="alert" className="mt-2 text-sm text-danger">Choose at least one duration.</p>}</fieldset><fieldset className="mt-5"><legend className="font-semibold">Strategy preferences</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{STRATEGIES.map(([value,label]) => <label key={value} className="flex min-h-11 items-center gap-2 rounded-xl border border-line px-3 text-sm"><input type="checkbox" checked={form.strategy_preferences.includes(value)} onChange={() => toggle('strategy_preferences', value)} />{label}</label>)}</div></fieldset></Surface>
    <Surface className="p-6"><h2 className="font-semibold">Approval boundary</h2><p className="mt-1 text-sm text-muted">External actions always require explicit approval and are never automated here.</p><label className="label mt-4">Internal reversible changes<select className="field mt-1" value={form.approval_strictness} onChange={event => { const value = event.target.value as PersonalPreferences['approval_strictness']; setForm(current => current ? { ...current, approval_strictness: value, internal_write_automation_enabled: value === 'always_ask' ? false : current.internal_write_automation_enabled } : current); }}><option value="always_ask">Always ask</option><option value="allow_reversible">Allow only when separately enabled</option></select></label><label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" disabled={form.approval_strictness !== 'allow_reversible'} checked={form.internal_write_automation_enabled} onChange={event => set('internal_write_automation_enabled', event.target.checked)} /><span><strong>Enable reversible internal plan changes</strong><span className="block text-muted">Off by default. This never enables external actions.</span></span></label></Surface>
    {(save.isError || reopen.isError) && <p role="alert" className="text-sm text-danger">{(save.error || reopen.error)?.message}</p>}{notice && <p role="status" className="text-sm text-success">{notice}</p>}<div className="flex flex-wrap gap-3"><button className="button-primary" disabled={save.isPending || form.preferred_focus_durations.length === 0 || form.strategy_preferences.length === 0}>{save.isPending ? 'Saving…' : 'Save personalization'}</button><button type="button" className="button-secondary" disabled={reopen.isPending} onClick={() => reopen.mutate()}>Reopen guided setup</button></div>
  </form>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: Array<readonly [string,string]>; onChange: (value: string) => void }) { return <label className="label">{label}<select className="field mt-1" value={value} onChange={event => onChange(event.target.value)}>{options.map(([key,text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
