import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, Clock3 } from 'lucide-react';
import { Link } from 'react-router-dom';
import FocusPanel from '../components/focus/FocusPanel';
import AppShell from '../components/layout/AppShell';
import { StrategyRecommendationCard } from '../components/strategy/StrategyRecommendationCard';
import { WhyThisPlan } from '../components/planning/WhyThisPlan';
import { EmptyState, ErrorState, LoadingState, PageHeader, Surface } from '../components/ui/primitives';
import { apiFetch, apiUrl, getApiErrorMessage } from '../lib/api';
import type { TodayResponse } from '../types/api';

async function loadToday(): Promise<TodayResponse> { const response = await apiFetch(apiUrl('/api/v1/today')); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Your day could not be loaded.')); return response.json(); }

export default function Today() {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['today'], queryFn: loadToday, refetchInterval: data => data.state.data?.active_focus_session?.status === 'active' ? 30_000 : false });
  const recovery = useMutation({ mutationFn: async (commitmentId: string) => { const response = await apiFetch(apiUrl(`/api/v1/rescue/${commitmentId}/plan`), { method: 'POST' }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'A recovery recommendation could not be prepared.')); return response.json(); }, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['today'] }) });
  const data = query.data;

  return <AppShell><PageHeader eyebrow="Today" title="A realistic day, at a glance" description="See what matters, choose the next action, and adjust only when reality requires it." action={<Link className="button-secondary" to="/inbox">Capture something</Link>} />
    {query.isPending ? <LoadingState label="Loading today’s plan" /> : query.isError ? <ErrorState message={query.error instanceof Error ? query.error.message : 'Your day could not be loaded.'} onRetry={() => query.refetch()} /> : !data || data.status === 'empty' ? <EmptyState title="Nothing is competing for your attention" message="Capture the commitments on your mind, then return here for a realistic next action." action={<Link className="button-primary" to="/inbox">Open Inbox</Link>} /> : <div className="space-y-5">
      <Surface className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className={`rounded-full p-2 ${data.status === 'attention' ? 'bg-danger-soft text-danger' : 'bg-success-soft text-success'}`}>{data.status === 'attention' ? <AlertTriangle className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}</div><div><p className="font-medium">{data.status_message}</p><p className="mt-3 text-sm text-muted">Next meaningful action</p><h2 className="mt-1 text-2xl font-semibold">{data.next_action?.title}</h2>{(data.next_action?.project || data.next_action?.outcome) && <p className="mt-1 text-sm font-medium text-accent-strong">{data.next_action.project?.title}{data.next_action.project && data.next_action.outcome ? ' · ' : ''}{data.next_action.outcome?.title}</p>}<p className="mt-2 text-sm text-muted">{data.next_action?.detail}</p></div></div></Surface>
      <FocusPanel session={data.active_focus_session} nextAction={data.next_action} />
      <div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Surface className="p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Ordered plan</h2><Link className="text-sm font-medium text-accent-strong hover:underline" to="/plan">Open Plan</Link></div><ol className="space-y-1">{data.ordered_plan.map((item, index) => <li key={item.id} className="flex items-center gap-4 rounded-xl px-3 py-3 hover:bg-surface-subtle"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent-soft text-xs font-semibold text-accent-strong">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{item.title}</p><p className="mt-0.5 flex items-center gap-1.5 text-xs capitalize text-muted"><Clock3 className="h-3.5 w-3.5" />{item.status.replaceAll('_', ' ')}</p></div></li>)}</ol></Surface><Surface className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">Attention</p><p className="mt-3 text-3xl font-semibold">{data.attention_count}</p><p className="mt-1 text-sm text-muted">items may need a decision.</p><p className="mt-4 text-sm text-muted">{data.pending_approval_count} approvals waiting</p></Surface></div>
      {data.strategy_recommendation && <StrategyRecommendationCard recommendation={data.strategy_recommendation} />}
      {data.explanation && <WhyThisPlan explanation={data.explanation} />}
      {!!data.routines_due?.length && <Surface className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">Due today</p><h2 className="mt-1 text-lg font-semibold">Routines</h2></div><Link className="text-sm font-medium text-accent-strong" to="/plan">Manage in Plan</Link></div><ul className="mt-3 space-y-2">{data.routines_due.map(routine => <li key={routine.id} className="rounded-lg bg-surface-subtle p-3"><span className="font-medium">{routine.title}</span><span className="ml-2 text-sm text-muted">{routine.preferred_time || 'Flexible'} · {routine.duration_minutes} min</span></li>)}</ul></Surface>}
      {data.recovery && <Surface className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-danger">Recovery</p><h2 className="mt-1 text-lg font-semibold">{data.recovery.title}</h2><p className="mt-2 text-sm text-muted">{data.recovery.reason}</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted">{data.recovery.options.map(option => <li key={option}>{option}</li>)}</ul><button className="button-secondary mt-4" disabled={recovery.isPending} onClick={() => recovery.mutate(data.recovery!.commitment_id)}>{recovery.isPending ? 'Preparing…' : 'Prepare recovery recommendation'}</button>{recovery.isSuccess && <p role="status" className="mt-3 text-sm text-success">Recommendation prepared for approval. No plan data changed.</p>}{recovery.isError && <p role="alert" className="mt-3 text-sm text-danger">{recovery.error.message}</p>}</Surface>}
    </div>}
  </AppShell>;
}
