import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import AppShell from '../components/layout/AppShell';
import { ErrorState, LoadingState, PageHeader, Surface } from '../components/ui/primitives';
import { StrategyRecommendationCard } from '../components/strategy/StrategyRecommendationCard';
import { apiFetch, apiUrl, getApiErrorMessage } from '../lib/api';
import type { WeeklyProposal, WeeklyView } from '../types/api';

async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await apiFetch(apiUrl(path), init); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Weekly planning could not complete.')); return response.json(); }
function mondayValue() { const day = new Date(); day.setDate(day.getDate() - ((day.getDay() + 6) % 7)); return day.toISOString().slice(0, 10); }

export default function Week() {
  const client = useQueryClient(); const [weekStart, setWeekStart] = useState(mondayValue()); const [proposal, setProposal] = useState<WeeklyProposal | null>(null); const [notice, setNotice] = useState('');
  const query = useQuery({ queryKey: ['week', weekStart], queryFn: () => request<WeeklyView>(`/api/v1/week?week_start=${weekStart}`) });
  const generate = useMutation({ mutationFn: () => request<WeeklyProposal>(`/api/v1/week/proposals?week_start=${weekStart}`, { method: 'POST' }), onSuccess: setProposal });
  const edit = useMutation({ mutationFn: (blocks: WeeklyProposal['blocks']) => request<WeeklyProposal>(`/api/v1/week/proposals/${proposal!.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ blocks }) }), onSuccess: value => { setProposal(value); setNotice('Weekly proposal updated and revalidated.'); } });
  const approve = useMutation({ mutationFn: () => request(`/api/v1/week/proposals/${proposal!.id}/approve`, { method: 'POST', headers: { 'Idempotency-Key': `weekly-${proposal!.id}` } }), onSuccess: async () => { setNotice('Weekly plan approved. Valid plan blocks were created.'); setProposal(null); await Promise.all([client.invalidateQueries({ queryKey: ['week'] }), client.invalidateQueries({ queryKey: ['plan'] }), client.invalidateQueries({ queryKey: ['today'] })]); } });
  const reject = useMutation({ mutationFn: () => request<WeeklyProposal>(`/api/v1/week/proposals/${proposal!.id}/reject`, { method: 'POST' }), onSuccess: () => { setNotice('Weekly suggestion rejected. No blocks were created.'); setProposal(null); } });
  return <AppShell><PageHeader eyebrow="Weekly planning" title="Decide what realistically fits" description="Review capacity, choose a small focus set, and approve only conflict-free blocks." action={<Link className="button-secondary" to="/plan">Back to daily Plan</Link>} />
    <div className="mb-5 flex flex-wrap items-end gap-3"><label className="label">Week starting<input aria-label="Week starting" type="date" className="field mt-1" value={weekStart} onChange={event => setWeekStart(event.target.value)} /></label><button className="button-primary" disabled={generate.isPending} onClick={() => generate.mutate()}>{generate.isPending ? 'Preparing…' : 'Suggest weekly focus'}</button>{notice && <p role="status" className="pb-2 text-sm text-success">{notice}</p>}</div>
    {(generate.isError || edit.isError || approve.isError || reject.isError) && <p role="alert" className="mb-4 text-sm text-danger">{generate.error?.message || edit.error?.message || approve.error?.message || reject.error?.message}</p>}
    {query.isPending ? <LoadingState label="Loading weekly capacity" /> : query.isError ? <ErrorState message={query.error.message} onRetry={() => query.refetch()} /> : query.data && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{query.data.days.map(day => <Surface key={day.date} className="p-4"><p className="text-xs font-semibold uppercase text-muted">{new Date(`${day.date}T12:00:00`).toLocaleDateString([], { weekday: 'short' })}</p><p className="mt-2 text-xl font-semibold">{day.remaining_minutes} min</p><p className="mt-1 text-xs text-muted">of {day.available_minutes} available</p>{day.over_capacity_minutes > 0 && <p className="mt-2 text-xs text-danger">{day.over_capacity_minutes} min over</p>}</Surface>)}</div>
      {query.data.primary_strategy && <StrategyRecommendationCard recommendation={query.data.primary_strategy} />}
      <div className="grid gap-5 lg:grid-cols-3"><Surface className="p-5"><h2 className="font-semibold">Outcomes due soon</h2>{query.data.due_outcomes.length ? <ul className="mt-3 space-y-2 text-sm">{query.data.due_outcomes.map(item => <li key={item.id} className="rounded-lg bg-surface-subtle p-3"><span className="font-medium">{item.title}</span><span className="mt-1 block text-xs capitalize text-muted">{item.status}</span></li>)}</ul> : <p className="mt-2 text-sm text-muted">No outcomes are due in the next two weeks.</p>}</Surface><Surface className="p-5"><h2 className="font-semibold">Important unscheduled work</h2>{query.data.unscheduled_work.length ? <ul className="mt-3 space-y-2 text-sm">{query.data.unscheduled_work.slice(0, 6).map(item => <li key={item.id}>{item.title}</li>)}</ul> : <p className="mt-2 text-sm text-muted">No important work is waiting for time.</p>}</Surface><Surface className="p-5"><h2 className="font-semibold">Routines this week</h2>{query.data.routine_occurrences.length ? <ul className="mt-3 space-y-2 text-sm">{query.data.routine_occurrences.map(item => <li key={item.routine_id}>{item.title} · {item.occurrences.length} occurrences{item.continuity_recovery && <span className="block text-xs text-accent-strong">Smaller restart available</span>}</li>)}</ul> : <p className="mt-2 text-sm text-muted">No active routines are scheduled.</p>}</Surface></div>
    </div>}
    {proposal && <Surface className="mt-5 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-accent-strong">Review required</p><h2 className="mt-1 text-xl font-semibold">Small weekly focus set</h2><p className="mt-2 text-sm text-muted">{proposal.explanation.summary}</p><div className="mt-4 space-y-3">{proposal.blocks.map((block, index) => <div key={`${block.commitment_id}-${block.start_at}`} className="grid gap-3 rounded-xl bg-surface-subtle p-4 sm:grid-cols-[1fr_180px]"><div><h3 className="font-medium">{block.title}</h3><p className="mt-1 text-sm text-muted">{new Date(block.start_at).toLocaleString([], { timeZone: query.data?.timezone })}</p></div><label className="label">Duration<select aria-label={`Duration for ${block.title}`} className="field mt-1" value={block.duration_minutes} onChange={event => { const blocks = proposal.blocks.map((item, itemIndex) => itemIndex === index ? { ...item, duration_minutes: Number(event.target.value) } : item); setProposal({ ...proposal, blocks }); }}><option value="20">20 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label></div>)}</div>{proposal.deferred.length > 0 && <div className="mt-4"><h3 className="font-medium">Deferred explicitly</h3><ul className="mt-2 space-y-1 text-sm text-muted">{proposal.deferred.map(item => <li key={item.id}>{item.title}: {item.reason}</li>)}</ul></div>}<p className="mt-4 text-xs text-muted">Deterministic · no blocks are created until approval.</p><div className="mt-4 flex flex-wrap gap-2"><button className="button-primary" disabled={approve.isPending} onClick={() => approve.mutate()}>{approve.isPending ? 'Approving…' : 'Accept weekly plan'}</button><button className="button-secondary" disabled={edit.isPending} onClick={() => edit.mutate(proposal.blocks)}>{edit.isPending ? 'Checking…' : 'Save edits'}</button><button className="button-secondary" disabled={reject.isPending} onClick={() => reject.mutate()}>{reject.isPending ? 'Rejecting…' : 'Reject suggestion'}</button></div></Surface>}
  </AppShell>;
}
