import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { apiFetch, apiUrl, getApiErrorMessage } from '../../lib/api';
import type { ExternalProposal, ProjectSummary } from '../../types/api';
import { Surface } from '../ui/primitives';

async function loadProposals() { const response = await apiFetch(apiUrl('/api/v1/integrations/proposals/pending')); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'External suggestions are unavailable.')); return response.json() as Promise<{ proposals: ExternalProposal[] }>; }
async function loadProjects() { const response = await apiFetch(apiUrl('/api/v1/projects')); if (!response.ok) return { projects: [] as ProjectSummary[] }; return response.json() as Promise<{ projects: ProjectSummary[] }>; }

export function ExternalProposals() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['external-proposals'], queryFn: loadProposals }); const projects = useQuery({ queryKey: ['projects'], queryFn: loadProjects }); const [choices, setChoices] = useState<Record<string, { action: string; project: string }>>({});
  const refresh = async () => Promise.all([client.invalidateQueries({ queryKey: ['external-proposals'] }), client.invalidateQueries({ queryKey: ['today'] }), client.invalidateQueries({ queryKey: ['projects'] })]);
  const approve = useMutation({ mutationFn: async ({ id, action, project }: { id: string; action: string; project: string }) => { const response = await apiFetch(apiUrl(`/api/v1/integrations/proposals/${id}/approve`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action_type: action, project_id: project || null }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'The suggestion could not be accepted.')); }, onSuccess: refresh });
  const dismiss = useMutation({ mutationFn: async (id: string) => { const response = await apiFetch(apiUrl(`/api/v1/integrations/proposals/${id}/decision`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision: 'dismissed' }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'The suggestion could not be dismissed.')); }, onSuccess: refresh });
  if (query.isPending) return <Surface className="mb-5 p-5"><p className="text-sm text-muted">Checking external context…</p></Surface>;
  if (query.isError) return <Surface className="mb-5 p-5"><p role="alert" className="text-sm text-danger">External suggestions are unavailable. <button className="font-semibold underline" onClick={() => query.refetch()}>Try again</button></p></Surface>;
  if (!query.data?.proposals.length) return null;
  return <Surface className="mb-5 p-5"><h2 className="font-semibold">From connected sources</h2><p className="mt-1 text-sm text-muted">Review these separately. Nothing is added automatically.</p><div className="mt-4 space-y-4">{query.data.proposals.map(proposal => { const choice = choices[proposal.id] ?? { action: proposal.action_type, project: '' }; return <article key={proposal.id} className="rounded-xl border border-line p-4"><p className="text-xs font-semibold uppercase tracking-wide text-accent-strong">{proposal.provider ?? 'External source'}</p><h3 className="mt-1 font-medium">{proposal.safe_summary}</h3><details className="mt-2 text-sm"><summary className="cursor-pointer font-medium">Inspect source</summary><p className="mt-2 text-muted">{proposal.source_excerpt || 'Open the connected source for full context.'}</p></details><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="label">Accept as<select className="field mt-1" value={choice.action} onChange={event => setChoices(current => ({ ...current, [proposal.id]: { ...choice, action: event.target.value } }))}><option value="create_task">Task</option><option value="create_outcome">Outcome</option><option value="create_event">Event</option><option value="create_reference">Reference</option></select></label><label className="label">Project (optional)<select className="field mt-1" value={choice.project} onChange={event => setChoices(current => ({ ...current, [proposal.id]: { ...choice, project: event.target.value } }))}><option value="">No project</option>{projects.data?.projects.map(project => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label></div><div className="mt-3 flex gap-2"><button className="button-primary" disabled={approve.isPending} onClick={() => approve.mutate({ id: proposal.id, action: choice.action, project: choice.project })}>Accept</button><button className="button-secondary" disabled={dismiss.isPending} onClick={() => dismiss.mutate(proposal.id)}>Dismiss</button></div></article>; })}</div>{(approve.isError || dismiss.isError) && <p role="alert" className="mt-3 text-sm text-danger">{(approve.error || dismiss.error)?.message}</p>}</Surface>;
}
