import { useEffect, useRef, useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { X } from 'lucide-react';
import { apiFetch, apiUrl, getApiErrorMessage } from '../../lib/api';
import type { RecoverySummary } from '../../types/api';

type Proposal = { id: string; payload_json: { rationale?: string; trade_off?: string; expected_impact?: string; feasible?: boolean; feasibility_reason?: string }; explanation: string };

export function RecoveryDialog({ recovery, onClose }: { recovery: RecoverySummary; onClose: () => void }) {
  const dialog = useRef<HTMLDivElement>(null); const queryClient = useQueryClient(); const [proposals, setProposals] = useState<Proposal[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { const root = dialog.current; const focusable = () => Array.from(root?.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])') ?? []); focusable()[0]?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'Tab') { const items = focusable(); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', handler); return () => document.removeEventListener('keydown', handler); }, [onClose]);
  const prepare = useMutation({ mutationFn: async () => { const response = await apiFetch(apiUrl(`/api/v1/rescue/${recovery.commitment_id}/plan`), { method: 'POST' }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Recovery options are temporarily unavailable.')); return response.json() as Promise<{ proposals: Proposal[]; ai_used: boolean }>; }, onSuccess: data => { setProposals(data.proposals.slice(0, 3)); setNotice(data.ai_used ? 'Options were model-assisted and checked against your plan.' : 'Using deterministic recovery options while AI guidance is unavailable.'); } });
  const choice = useMutation({ mutationFn: async ({ choice, optionId }: { choice: 'used' | 'dismissed' | 'postponed'; optionId?: string }) => { const response = await apiFetch(apiUrl('/api/v1/rescue/choices'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ recommendation_key: recovery.recommendation_key, choice, failure_mode: recovery.failure_mode, option_id: optionId }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'Your choice could not be saved.')); }, onSuccess: (_, variables) => { if (variables.choice !== 'used') onClose(); } });
  const approve = useMutation({ mutationFn: async (proposalId: string) => { const response = await apiFetch(apiUrl(`/api/v1/rescue/proposals/${proposalId}/approve`), { method: 'POST', headers: { 'Idempotency-Key': `recovery-${proposalId}` } }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'That recovery option could not be applied.')); return proposalId; }, onSuccess: async proposalId => { await choice.mutateAsync({ choice: 'used', optionId: proposalId }); await Promise.all([queryClient.invalidateQueries({ queryKey: ['today'] }), queryClient.invalidateQueries({ queryKey: ['plan'] })]); setNotice('Recovery approved and applied.'); } });
  return <div role="presentation" className="fixed inset-0 z-50 flex items-end justify-center bg-ink/40 p-0 sm:items-center sm:p-4" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="recovery-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-surface p-5 shadow-soft sm:rounded-2xl sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-accent-strong">Plan recovery</p><h2 id="recovery-title" className="mt-1 text-xl font-semibold">{recovery.title}</h2></div><button aria-label="Close recovery" className="icon-button" onClick={onClose}><X className="h-4 w-4" /></button></div><section className="mt-5 rounded-xl bg-surface-subtle p-4"><h3 className="font-medium">What changed</h3><p className="mt-1 text-sm text-muted">{recovery.what_changed}</p><p className="mt-3 text-xs font-semibold uppercase tracking-wide text-muted">Likely cause · {recovery.failure_mode.replaceAll('_', ' ')}</p></section>
    {!proposals.length && <div className="mt-5 space-y-3">{recovery.options.map(option => <article key={option.id} className={`rounded-xl border p-4 ${option.id === recovery.recommended_option_id ? 'border-accent bg-accent-soft/40' : 'border-line'}`}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium">{option.title}</h3>{option.id === recovery.recommended_option_id && <span className="text-xs font-semibold text-accent-strong">Recommended</span>}</div><p className="mt-2 text-sm text-muted">{option.rationale}</p><p className="mt-2 text-xs text-muted"><strong>Trade-off:</strong> {option.tradeoff}</p></article>)}</div>}
    {proposals.length > 0 && <div className="mt-5 space-y-3">{proposals.map((proposal, index) => <article key={proposal.id} className="rounded-xl border border-line p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium">Recovery option {index + 1}</h3>{index === 0 && <span className="text-xs font-semibold text-accent-strong">Recommended</span>}</div><p className="mt-2 text-sm text-muted">{proposal.payload_json.rationale || proposal.explanation}</p><p className="mt-2 text-xs text-muted"><strong>Trade-off:</strong> {proposal.payload_json.trade_off || 'Some work may move.'}</p><p className="mt-1 text-xs text-muted"><strong>Expected impact:</strong> {proposal.payload_json.expected_impact || 'A more credible plan.'}</p>{proposal.payload_json.feasible === false ? <p className="mt-3 text-sm text-danger">{proposal.payload_json.feasibility_reason}</p> : <button className="button-primary mt-3" disabled={approve.isPending} onClick={() => approve.mutate(proposal.id)}>Approve this option</button>}</article>)}</div>}
    {notice && <p role="status" className="mt-4 text-sm text-success">{notice}</p>}{(prepare.isError || approve.isError || choice.isError) && <p role="alert" className="mt-4 text-sm text-danger">{(prepare.error || approve.error || choice.error)?.message}</p>}<div className="mt-6 flex flex-wrap gap-2 border-t border-line pt-4">{!proposals.length && <button className="button-primary" disabled={prepare.isPending} onClick={() => prepare.mutate()}>{prepare.isPending ? 'Checking options…' : 'Review recovery options'}</button>}<button className="button-secondary" disabled={choice.isPending} onClick={() => choice.mutate({ choice: 'postponed' })}>Remind me later</button><button className="px-3 py-2 text-sm font-medium text-muted" disabled={choice.isPending} onClick={() => choice.mutate({ choice: 'dismissed' })}>Dismiss</button></div><p className="mt-3 text-xs text-muted">No plan changes until you approve a feasible option.</p></div></div>;
}
